# Generated by Django 4.0.6 on 2023-09-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('minutes', models.BigIntegerField()),
                ('days', models.JSONField(default=list)),
            ],
        ),
    ]
