# Generated by Django 4.0.6 on 2023-09-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_student_id_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='days_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
